### ISSUE TITLE
Comms diagram

### ISSUE THREAD

**Issue by cprezzi** [LaserWeb/lw.comm-server#1]
First draft of the communications design (by Peter van der Walt):
![comms](https://cloud.githubusercontent.com/assets/5457949/21324280/5f98ba8c-c621-11e6-978d-2691500f1cbf.png)

**Comment by cprezzi** [comment]
The backend (lw.comm-server) will have one unified interface for the frontend and handle all different (machine) connection interfaces and firmware protocolls.

Machines can be connected through:
* serial (USB or UART)
* Ethernet (LAN / WLAN).

The following firmware will be supportet (at first):
* Grbl (min. v1.1e)
* Smoothieware
* TinyG

**Comment by openhardwarecoza** [comment]
Slight correction: Ethernet on smoothie is a simple ajax/http_post
interface

Wifi is a Websocket server to serial running on an esp8266. (its also
firmware agnostic,  it just bridges serial to websocket and vice versa,
 and has a web interface to configure Wifi settings like AP and psk) so it
can even bridge Grbl

**Comment by openhardwarecoza** [comment]
One way to unify wifi and ethernet: Smoothieware supports a telnet
interface...  Havent used it yet but apparently closer to the serial
interface than ajax (though ajax/post is the only way to upload gcode to
sd).
For the esp,  esplink firmware also has the same telnet interface that
bridges to serial

**Comment by cprezzi** [comment]
Thanks for the hint. I'm still thinkering and writing down so I don't forget ;)

**Comment by openhardwarecoza** [comment]
Same here,  dropping notes as i recall them (:

**Comment by cprezzi** [comment]
TinyG is Websocket, if I remeber correctly.

**Comment by cprezzi** [comment]
Good to know about esplink, thanks.

**Comment by openhardwarecoza** [comment]
Tinyg is json over serial.  (for status and config)  - stringified json
anyway... But gcode gets fed same as others,  except instead of 'ok'  the
response is sr:*

**Comment by cprezzi** [comment]
Yes, I know there is a serial communication for TinyG, but I thought there is also an ethernet connection. I will investigate :)

**Comment by cprezzi** [comment]
Seems I'm wrong, only USB on TinyG and gShield (via Arduino Due).

**Comment by cprezzi** [comment]
@openhardwarecoza Can you give me the communication diagram in original file format? I'd like to adjust it a bit and add it to the Wiki.

**Comment by openhardwarecoza** [comment]
Lets see if the share works.  I drew it on Gliffy.com (free account) 
https://www.gliffy.com/go/publish/11458681

**Comment by openhardwarecoza** [comment]
There is a Duplicate button on that window

**Comment by cprezzi** [comment]
Jep, worked.
How did you export the graphic? Screenshot? I am not allowed to save as JPG (with free account).
