### ISSUE TITLE
Cannot connect from LaserGRBL

### ISSUE THREAD

**Issue by cezarypiatek** [LaserWeb/lw.comm-server#110]
Hi,

I installed `lw.comm-server` on RaspberryPi 2b. Using LaserWeb ui everything works fine. I can connect to my Sculpfun S10 connected to Raspberry. However, I wanted to use LaserGRBL as UI.

Settings as below

![image](https://user-images.githubusercontent.com/7759991/187492036-b719c701-e7fc-4785-98b2-a7495d286383.png)

![image](https://user-images.githubusercontent.com/7759991/187492067-22456ef4-3290-46c5-9e92-e95d0ebc27fd.png)

LaserGRBL cannot connect to the `lw.comm-server`. Do I need to configure anything more? Is it even possible to make this kind of connection? 

Thanks for the help.
Cezary

**Comment by cprezzi** [comment]
You should ask that to the LaserGRBL devs. 
Even if the protocol and source of lw.comm-server is open, we can't support frontends other than LaserWeb.
