### ISSUE TITLE
Merge dev_comms @LaserWeb4

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/lw.comm-server#12]
Branching off from  https://github.com/LaserWeb/lw.comm-server/issues/2#issuecomment-282974689

**Comment by cprezzi** [comment]
I did also merge my additions from today ;)

**Comment by openhardwarecoza** [comment]
Yay, so I can now use dev-es6 in the Electron build? Or not yet? (currently
using dev_comms)

**Comment by cprezzi** [comment]
Yes you can! 
I will merge further changes to dev-es6 once they are testet.

**Comment by cprezzi** [comment]
It would also be interesting to see how gh-pages work once they are updated!
It should be possible to run a local server and connect it from the gh-pages (without electron installation) ;)

**Comment by openhardwarecoza** [comment]
And also with electron --nogui (;
