### ISSUE TITLE
Inject into the serial stream

### ISSUE THREAD

**Issue by iceblu3710** [LaserWeb/lw.comm-server#13]
Is is possible to inject macros into the serial stream server side?

I will be running the comm server on a Raspberry Pi and would like to use the [OSMC remote ](https://osmc.tv/store/product/osmc-remote-control/) to jog around (using macros) and as the abort, feed hold, start buttons.

**Comment by cprezzi** [comment]
It's already possible to have multiple clients connecting the server at the same time. Each client could send commands to the connected machine. So you could programm a small app that translates remote commands to gcode and sends them to the server via the websocket API.

We could also think about a plugin-structure for the server, but first we need to release LW4.

**Comment by cprezzi** [comment]
The newst version has keyboard jogging, so simulated keystrokes should also work.
