### ISSUE TITLE
[Linux:x64] LaserWeb4-Installer fails

### ISSUE THREAD

**Issue by iceblu3710** [LaserWeb/lw.comm-server#14]
`sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils`

is required before `npm run dist` for a successful build on Linux.

As Per: [wiki/Multi-Platform-Build](https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build)

**Comment by iceblu3710** [comment]
Other than that the build is working perfectly. Definitely handy to just have a single file app to run!

**Comment by openhardwarecoza** [comment]
Added cross platform references to readme in commit https://github.com/LaserWeb/lw.comm-server/commit/cdd7c901c38d02b11de1b85fba16d7c5bf730345#diff-793b0ee07e5f385a2ebbfc1b26a10152
