### ISSUE TITLE
Error handling for EADDRINUSE 

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/lw.comm-server#20]
Quite regularly we get users who are trying to run two lw4 instances, or for example have lw3 open, then run lw4. 

CMD and Electron both popup a generic EADDRINUSE error.   Wondering if its possible for us to catch the error and rather print our own error message explaining to the user that an instance thats already open needs to be closed or something to that effect

**Comment by openhardwarecoza** [comment]
http://stackoverflow.com/questions/9544479/how-do-i-catch-node-js-express-server-errors-like-eaddrinuse

**Comment by openhardwarecoza** [comment]
https://www.nallex.com/questions/example-of-how-to-handle-eaddrinuse-errors-in-nodejs

**Comment by openhardwarecoza** [comment]
![eaddr](https://cloud.githubusercontent.com/assets/7695323/24258812/8dedbc14-0ff7-11e7-8988-65dfc6042123.PNG)

**Comment by DarklyLabs** [comment]
@cprezzi Hi Claudio, do you have any resolutions to capturing this error?
It is being reported by many LW4 users.

**Comment by jorgerobles** [comment]
Maybe we can specify a range of ports and if catch error open other port (809x).
Downside could be the fill up of all the alternative ports. Have to say 8000/8080 are pretty common ports, maybe we can move to 90xx

**Comment by jorgerobles** [comment]
Also maybe https://www.npmjs.com/package/node-netstat could be useful, scanning first if that port is used...

**Comment by jorgerobles** [comment]
@DarklyLabs have you experienced that error? If so, could use a network diagnose tool to know what is on 8000? Maybe LW is not cleaning up correctly on binary or there's a common software that uses that port.

**Comment by DarklyLabs** [comment]
Is it possible to only allow one instance of LW to run on a computer at any time?
We have found situations where the computer has gone to sleep and upon awakening chrome crashed but there is still an instance of LW running when we check the processes.

**Comment by DarklyLabs** [comment]
@jorgerobles We can replicate the error by starting 2 instances of LW.

**Comment by jorgerobles** [comment]
Yes, as it's using a specific port to launch, means that if is used conflicts each other. 
The problem here is the new instance cannot kill the former. Will investigate.

 Thanks for the feedback!

**Comment by jorgerobles** [comment]
@cprezzi  https://github.com/electron/electron/blob/master/docs/api/app.md#appmakesingleinstancecallback

**Comment by cprezzi** [comment]
@jorgerobles Thanks. I will insert the makeSingleInstance into the electron code. That's the most common reason for this error. I probably also need to implement a netstat check if the port is already used by another server.

**Comment by cprezzi** [comment]
I have implemented the makeSingleInstance function to prohibit starting multiple instances. Instead, the main window is activated.
See commit https://github.com/LaserWeb/lw.comm-server/commit/905cde1913641ec99b8075baaa1af299c9c7792a
