### ISSUE TITLE
electron_bundler and master out of sync

### ISSUE THREAD

**Issue by jorgerobles** [LaserWeb/lw.comm-server#21]
Electron_bundler branch is way past master. Can they amend? @cprezzi

**Comment by cprezzi** [comment]
I see that the electron_bundler branch is ahead of master by 47 commits but only 1 commit behind and that 1 commit I have manually done in electron_bundler.
see https://github.com/LaserWeb/lw.comm-server/network

**Comment by openhardwarecoza** [comment]
Brough master: v.0.4.50 into electron_bundler with https://github.com/LaserWeb/lw.comm-server/commit/9a972bd141d8187a5986d5aa27f64d33420d7002

Now only electron_bundler is ahead (and those are all electron or buildscript related commits)
