### ISSUE TITLE
Set zero failure with grbl

### ISSUE THREAD

**Issue by tbfleming** [LaserWeb/lw.comm-server#29]
Set Zero produces ```error:undefined```. It looks like there are 3 bugs involved.

![image](https://cloud.githubusercontent.com/assets/418464/26036503/e20a9f14-38ac-11e7-8268-0afb99fcdfab.png)

1. Funny characters in addQ()
2. Stock grbl doesn't understand ```A0```
3. Error replies from grbl get mangled

**Comment by cprezzi** [comment]
I see. The A0 in the "all" case is causing the problem, as the 'SetZero' button on LW4 uses this case.
I have removed the A0 from this case and made a new case 'xyza' for zeroing all axis.

Should be solved by commit https://github.com/LaserWeb/lw.comm-server/commit/2cc95d319af047a023fc032250d01478ed5282d1
