### ISSUE TITLE
How to use get-bounds

### ISSUE THREAD

**Issue by cprezzi** [LaserWeb/lw.comm-server#3]
@tbfleming For the `check size` function in the jog tab I need the bounds of the actual gcode.
Can I use your get-bounds.js for this? If yes, how do I have to use it?

**Comment by tbfleming** [comment]
get-bounds.js gets the bounds of a React component; no existing code gets gcode bounds. You may have to use tmpParseGcode.js.

**Comment by cprezzi** [comment]
I realized that after writing the issue, sorry.
I just thought there must be some code, because you show the width and height of an object in the placing popup. Wouldn't it be best if the gcode class had these properties?

**Comment by tbfleming** [comment]
The placing popup edits documents, not gcode. The Gcode class is dead code; it's the now-removed gcode tab.

**Comment by cprezzi** [comment]
I made a simple solution by parsing all X and Y values in the gcode.  This is not perfect, because all moves are taken into account (incl. G0), which means that the bounding box includes the origin and not only the cutting part.

**Comment by cojarbi** [comment]
I think that's good and similar to what we have in LW3. It useful in conjunction with a diode pointer or the test button to place the stock into location

**Comment by cprezzi** [comment]
Right, that's why I implemented it and already pushed it to dev-es6 too ;)
