### ISSUE TITLE
Source?

### ISSUE THREAD

**Issue by bullestock** [LaserWeb/lw.comm-server#32]
Looking at the files in app/, it looks as if they have been generated from some other files - if yes, where is the actual source code?

**Comment by jorgerobles** [comment]
Source files are not on distribution, as are packed with webpack.

**Comment by bullestock** [comment]
Yes, that confirms my suspicion. But where is the source, then?

**Comment by jorgerobles** [comment]
https://github.com/LaserWeb/lw.comm-server/blob/master/server.js

2017-06-07 10:58 GMT+02:00 Torsten Martinsen <notifications@github.com>:

**Comment by cprezzi** [comment]
The app folder contains a compiled version of LaserWeb4 dev environment (built by `npm run bundle-dev` in LW4 folder) and copied over to lw.comm-server by `npm run update_lw4`.
