### ISSUE TITLE
Trying to Unify electron_bundler branch and master 

### ISSUE THREAD

**Issue by jorgerobles** [LaserWeb/lw.comm-server#33]
Hi. I've observed some growing differences on electron_bundler and master. I've patched electron_bundler but if you could, please take a look to try to ammend branches, or we have to find a new configuration pattern to binaries.

**Comment by cprezzi** [comment]
What growing differences do you mean (beside of the additions I made)?

**Comment by jorgerobles** [comment]
Dissapeared some bundle scripts,  app info and changed conflicting libraries on merge :/

**Comment by cprezzi** [comment]
So mainly changes in package.json?

**Comment by cprezzi** [comment]
How could we tell git not to merge package.json?

**Comment by tbfleming** [comment]
I don't think git has an option like that. Plus, we do add dependencies to package.json which should be merged.

**Comment by jorgerobles** [comment]
Maybe we should approach a bootstrap that uses server packaging decoupling
electron build from server from frontend. Don't know if makes sense, thought

**Comment by cprezzi** [comment]
@tbfleming I was talking about package.json of lw.comm-server, which doesn't have many dependencies.

**Comment by cprezzi** [comment]
@jorgerobles What does electron exactly need to host the frontend and start the node server? Could that also be bundled from LW4 repo? And would that make more sense?

**Comment by cprezzi** [comment]
@jorgerobles I have now merged the contents of package.json from electron_bundler back to master.
To avoid further problems, we should make all changes on master and merge them later to electron_bundler.

**Comment by openhardwarecoza** [comment]
How about packing lw.comm-server as electron too, but listen for say --no-gui switch then just dont run the Electron.Window code?

**Comment by openhardwarecoza** [comment]
ie, wrap https://github.com/LaserWeb/lw.comm-server/blob/electron_bundler/server.js#L2670-L2741 in a IF

**Comment by openhardwarecoza** [comment]
In terms of package.json, electron build only has more dependencies and the build scripts.  Apart from a larger initial npm install, may as well be the same package.json for Master.   If you consider only distributing comms-server as per https://github.com/LaserWeb/lw.comm-server/issues/33#issuecomment-307820923 then no one needs to npm install anyway except the devs who build the bins

**Comment by jorgerobles** [comment]
Maybe we are talking the same and we don't know. Compiling Lw-comm-server as electron will weight a lot. @cprezzi  https://github.com/LaserWeb/lw.comm-server/issues/33#issuecomment-307447289 comment could work, trying again to translate electron build to Frontend, keeping Server as a package. On the other side, frontend has no binary dependencies yet.

Or maybe we are just looking for green dogs. Having the package.json solved could be just fine.

**Comment by cprezzi** [comment]
@openhardwarecoza The Electron code is not needed in the master branch, as changes to server.js will never overwrite the electron code in the elevtron_bundler branch when merged.

**Comment by cprezzi** [comment]
We have some users that use lw.comm-server standalone, on raspi for exampe, and I don't like to blow up the package size (and potential errors) for those users.

**Comment by cprezzi** [comment]
Package.json in master is now near identical as in electron_bundler.
see https://github.com/LaserWeb/lw.comm-server/commit/70ae8e1b8d7d942cc26766b98c366678aef89229
