### ISSUE TITLE
LW4 integration - small cosmetic bug

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/lw.comm-server#4]
Dropdown behind input

![overlap](https://cloud.githubusercontent.com/assets/7695323/23104830/c1ae7918-f6dd-11e6-9b52-3f33f85bf867.png)

**Comment by cprezzi** [comment]
That seems to be a general problem with the Select fields in forms.js. It happens when the overlaying element was invisible first and later showed by react/redux code. 
I didn't analyse further, but I think it could be fixed by a css z-index. Will check...

**Comment by cprezzi** [comment]
Solved (in LW4 src/styles/forms.css)
