### ISSUE TITLE
Home Z crash server

### ISSUE THREAD

**Issue by jorgerobles** [LaserWeb/lw.comm-server#41]
Just did Home Z :cry:

C3D with SmoothieWare CNC latest version

![image](https://user-images.githubusercontent.com/1706080/27836301-1e06f9d6-60df-11e7-9960-687cfc3f6906.png)

**Comment by cprezzi** [comment]
Did you see the `Smoothieware detected (...)` string in the console? 
Could you please test if `G28.2 Z` is working correctly of delivering the same error?

**Comment by jorgerobles** [comment]
![image](https://user-images.githubusercontent.com/1706080/27837125-c951e9c4-60e2-11e7-8952-f7d36068bb4d.png)

G28.2 Z Works fine

**Comment by tbfleming** [comment]
My heart skipped a beat when I read the first 3 words of the title: "Home Z crash"

**Comment by cprezzi** [comment]
Ok, found the error. Typo in the firmware name (smothie insted of smoothie). Fixed with commit https://github.com/LaserWeb/lw.comm-server/commit/cc3741595ecd5e4f49fec4e25b5f1303e71859e8

**Comment by jorgerobles** [comment]
Great!!
