### ISSUE TITLE
Z work offsets incrementing with homing

### ISSUE THREAD

**Issue by domenic-d** [LaserWeb/lw.comm-server#43]
Z work offset keep incrementing by 10mm every time a homing is performed.

![screen shot 2017-07-19 at 8 34 19 am](https://user-images.githubusercontent.com/27034222/28342805-63ab1be6-6c5d-11e7-82eb-060738604bef.png)

**Comment by cprezzi** [comment]
It seems you are not using the firmware-cnc right? Otherwise there should be a second line after the Firmware detection saying `CNC Build 3 axis`.

**Comment by cprezzi** [comment]
![grafik](https://user-images.githubusercontent.com/5457949/28365535-4db068c4-6c89-11e7-8256-03635407e9b1.png)

**Comment by cprezzi** [comment]
Unfortunately I do not have a machine with Z-Axis and smoothie at the moment, so I can't test myself.

**Comment by cprezzi** [comment]
The firmware in your screenshot is firmware.bin from 27 Nov 2016! 
Please try [firmware-cnc.bin](https://github.com/Smoothieware/Smoothieware/blob/edge/FirmwareBin/firmware-cnc.bin) from 24 Apr 2017 as recommended.

**Comment by domenic-d** [comment]
We are using this version because it has been working correctly for our machine.  In case you were not aware, updating the firmware for a certified product, such as ours, is not a straight forward process. There are many organisations to be notified and paperwork that needs to be officially generated.

The cnc version of the firmware also makes a significant change to the way G28 is handled and this would cause all our existing customer's machines to stop functioning correctly unless they all performed the updates. 

Having said all this, we will have to work through this and resolve it at our end. It is unfortunate that consideration for legacy support was not made when this change was made.

**Comment by tbfleming** [comment]
LW4 was a fresh start. If I remember right, we've always said LW4 needed the -cnc version.

**Comment by domenic-d** [comment]
Installed the latest smoothie 
firmware CNC version.
Problem still exists.

![Uploading Screen Shot 2017-07-20 at 3.32.47 pm.png…]()

**Comment by cprezzi** [comment]
@domenic-d There was issues in smoothieware that have been solved since last november and some new features was added, that we use too. Did you realy plan to stay with this version for Years?

The LaserWeb Porject needs to stay up-to-date with the latest firmwares and often we depend on new firmware features.

**Comment by cprezzi** [comment]
@domenic-d Now to your problem: 
- Could you please provide your smoothie config file?
- Please provide your LW settings and machine profiles (export from settings/tools)?
- How is your mechanical endstop configuration (microswitch/optical, NO/NC, to GND/5V)? 

@openhardwarecoza @cojarbi Could you please try to replicate this behaviour?

**Comment by openhardwarecoza** [comment]
No homing switches installed. Sorry (:

**Comment by cprezzi** [comment]
@domenic-d 
- Which OS and LW version did you use? 
- Did you test this with a USB cable or/and your bluethooth bridge? (any difference?)

**Comment by cojarbi** [comment]
Me neither. I will prep a machine soon

**Comment by domenic-d** [comment]
We have tested this further and found that the homing commands we were using was causing the problem. With the CNC version of the firmware, the G28.X commands must be used to ensure this issue doesn't arise.
For reference in case others have this problem:

**Original Homing Sequence**
G0Z60
G92Z50
G28X0Y0

**Revised homing sequence**
G0Z60
G28.3Z50
G28.2XY

Apologies for this false alarm and thank you for the help.

**Comment by openhardwarecoza** [comment]
Remember to update your lw. Machines profiles so your profiles get included
