### ISSUE TITLE
serialport 4.0.7 wont build with node 10

### ISSUE THREAD

**Issue by gdunstone** [LaserWeb/lw.comm-server#56]
trying to install on a raspberry pi like soc (odroid xu4) running ArchLinux causes some build fails because serialport 4.0.7 is outdated.

is it possible to update the implementation of serialport to 6.x.x so I can unignore node?

**Comment by cprezzi** [comment]
The actual lw.comm-server is based on nodejs 6 (as you can find in the raspi installation guide of the wiki).
Migrating to actual serialport lib and nodejs 8 (LTS) is not a simple task and needs lots of tests, which I don't have time for at the moment.

**Comment by gdunstone** [comment]
OK that's fine.
I'll see if I can whip up a docker image or something.
