### ISSUE TITLE
Serialport has vulnerabilities

### ISSUE THREAD

**Issue by jorgerobles** [LaserWeb/lw.comm-server#59]
Hi,

I've got a report from github about a package named hoek to be upgraded. https://github.com/LaserWeb/LaserWeb4/network/dependencies
That package goes inside serialport.

**Comment by cprezzi** [comment]
This message comes from package-lock.json, which would not be built with the correct nodejs version 6. I guess you updated to nodejs 8, which created this package-lock.json.
You could try to delete package-lock.json so it can be created again with a never version of hoek, or go back to nodejs 6.

**Comment by cprezzi** [comment]
Closed, as we moved to Serialport 6.2.2
