### ISSUE TITLE
Electron - Build

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/lw.comm-server#6]
Morning

I integrated Electron-Builder into lw.comms-server itself 

1.  Basically, I copy laserweb4/dist to app/lw4 (we can later remove your test/app and replace it with lw4's html)

2.  I created a ./build/ directory to contain the icons/bg (hardcoded paths/filenames which electron expects to be what they are: http://electron.rocks/electron-builder-explained/)

3.  Then in server.js at the very bottom we handle the electron gui

4.  Lastly, in package.json I added two more scripts, and the build{} json for Electron-builder

I tested briefly and it didnt seem to break your normal workflows (lw4 start-all, and standalone lw.comm-server)

I also tested the built electron app and comms seem to be running.  

https://github.com/electron-userland/electron-builder/issues/974 used to be an issue, but as of this build its no longer an issue.  I suspect the bug got fixed somewhere in one of the dependencies and now just work (:  Yay

**Comment by jorgerobles** [comment]
Great!! Hope to test today :)

**Comment by openhardwarecoza** [comment]
Good stuff... Time crept up on us... @DarklyLabs starts shipping Emblasers this week, and @FabCreator will allow customers to collect their Fabkits on the 24th (shipping remainder the week after) - so I expect LW to have a rather busy week on the final testing of all this + support as users start receiving their machines

**Comment by openhardwarecoza** [comment]
@Vertigotech - installer build instructions over on  https://github.com/LaserWeb/lw.comm-server/blob/master/README-ELECTRON.md - done - now you dont need to distribute rogue EXEs 
Please help test the build process and built app and once we are all happy (in a week or so) we can make EXEs/BINs/DMGs available for users to download directly from github.com/LaserWeb

**Comment by openhardwarecoza** [comment]
Ahh, grr, found my first issue @tbfleming - dragging items on cam tab doesnt work.

**Comment by openhardwarecoza** [comment]
Ok hold up (: I had Electron 1.4.1   - 1.6+ is on Chrome 56...

**Comment by cprezzi** [comment]
@openhardwarecoza During testing I embedded lw.comm-server as dependency in LaserWeb4 and started both application toghtery (if needed) in packet.json of LaserWeb4. This way I was able to choose what I want to start with `npm start` (both) or `npm start-server` or `npm start-app`.

You flipped it around and included the app (LW4) in lw.comm-server (like it was on LW3).

But what about this scenario:
- Server started separately on a PC/Raspi... (not hosting the app)
- App installed (manual or elektron) on a PC/Notebook without server
- App connecting server on other machine. 

I would prefer to leave lw.comm-server as a separate, independent package (unified communications server) that can also be used by other frontends via the api.

Couldn't the electron compile also be made in LaserWeb4? This way we would have the options to compile installers with or without included server.

**Comment by openhardwarecoza** [comment]
I tried that initially in LaserWeb4-Installer. Electron needs a node
backend to start,  and it needs a webserver running to host the UI on.

Feel free to refactor,  but nb we owe Darkly a working solution asap (last
week)  so quick wins to get going now is better than not going at all.

**Comment by openhardwarecoza** [comment]
Honestly it hasnt made major changes except including lw's compiled dist in
the exe.  Apart from that change all i did was make node server.js into an
electron app (which would also be the best way to distribute lw.comm-server
as a standalone app (like spjs)

It already has a webserver.

In lw2 days i would have left out the webserver and told people to use
ghpages,  then run the server locally.  I also remember the backlash  that
decision had -  rioting users who dont have wifi in their garages...

The history of lw does make a lot of decisions for us

**Comment by cprezzi** [comment]
At least you should make a separate electron branch and leave master slick and clean for separate usage.

**Comment by openhardwarecoza** [comment]
Fine gimme 30 and i'll revert everything

**Comment by openhardwarecoza** [comment]
Done

I'm out. Good luck

**Comment by cprezzi** [comment]
@openhardwarecoza I didn't want to offend you in any way! I appreciate your opinion!!
I just wanted to stay slim with the server.

**Comment by jorgerobles** [comment]
@openhardwarecoza, @cprezzi  I've got Peter's code from yesterday in my computer. I could open a branch. @openhardwarecoza do you agree? I will be sad if we lost the work you did. :cat:

**Comment by openhardwarecoza** [comment]
Glad you did.  Git reset killed my local work

**Comment by jorgerobles** [comment]
Available on https://github.com/LaserWeb/lw.comm-server/tree/electron_bundler

**Comment by cprezzi** [comment]
@jorgerobles Thank you much!

@openhardwarecoza I am sad that you felt so negative about my statements. I did not mean it like that!

**Comment by jorgerobles** [comment]
@openhardwarecoza could you restore the installation wiki page, plz? :smile:

**Comment by openhardwarecoza** [comment]
Installation of electron?  Was a readme-electron.md inside the repo (: -  wasnt on the wiki

**Comment by openhardwarecoza** [comment]
https://github.com/LaserWeb/lw.comm-server/blob/electron_bundler/README-ELECTRON.md

**Comment by jorgerobles** [comment]
Oh, ok sorry, slipped that.

**Comment by openhardwarecoza** [comment]
No problem.  I probably should have wiki'd it instead

**Comment by jorgerobles** [comment]
I've added `git checkout electron_bundler &&\` because the branch is different now.
I've run the build script but get a blank screen (OSX) :|

**Comment by openhardwarecoza** [comment]
Well, one of three things:

1) in https://github.com/LaserWeb/lw.comm-server/blob/electron_bundler/server.js#L1838 uncomment and see if the devtools give any clues

2)  Try electron 1.4x (I also noticed just before trashing my work https://github.com/LaserWeb/lw.comm-server/issues/6#issuecomment-281307654 - i was still using Electron 1.4x and that worked. When I uninstalled Electron 1.4 and installed 1.6, i also had a blank screen

2.1  If thats the case, then it means https://github.com/electron-userland/electron-builder/issues/974 might be back :(
2.1.1  running 'electron .' instead of npm run dist, should launch a live version:  If that works, but the built dmg/asar doesnt, then  its https://github.com/electron-userland/electron-builder/issues/974
2.1.2  If it also brings up a blank screen under live electron, its something else

3.  The server.js webserver on port 8000 serves the page that electron has to display:  So a quick check on chome :8000 should also help (if it displays in chrome, then server.js is serving it fine, but electron doesnt render it?

**Comment by jorgerobles** [comment]
Wow, thanks! I will report news ;)

**Comment by cprezzi** [comment]
The lw.comm-server package is also included in lw4's package.json. Could that cause a problem when bundling it again with electron?

Also: LW4 uses port 8080 by default, but the webserver of lw.comm-server is on port 8000.

**Comment by cprezzi** [comment]
On line 111 of server.js there is still the folder `./app` serverd as the web page. Shouldn't that be `./app/lw4` for the lw4 pages?
(see https://github.com/LaserWeb/lw.comm-server/blob/electron_bundler/server.js#L111)

**Comment by openhardwarecoza** [comment]
@cprezzi nope thats still fine.   ./app is served by node static, but the webserver will handle subdirectories (otherwise /js and /lib wont get served either) 

As a test running node server.js in there, and accesing localhost:8000/lw4 should bring it up 

https://github.com/LaserWeb/lw.comm-server/blob/electron_bundler/server.js#L1825 loads up the window into electron

In this sense we really are running lightweight.  server.js still does everything it did (webserver, usb, etc) only, at the very bottom, we launch a electron window (aka fullscreen slimmed down chrome browser)

that loads up webserver content from server.js:8000

**Comment by cprezzi** [comment]
@openhardwarecoza Ah ok, didn't see that electron specific line. Have you tried to use localhost instead of 127.0.0.1? I had that problem on my Win10 System.

**Comment by openhardwarecoza** [comment]
I am busy re npm'ing it now (+-500mb total @60kbps link... driving me slowly insane)

**Comment by cprezzi** [comment]
Ok, I leave you. I'm anyways a electron noob.

**Comment by openhardwarecoza** [comment]
hehe no problem. we are only scratching the skin.... Once we get this ball through the gate theres still a hundred more (asar auto update servers with nutz/squirrel, being a high priority)

**Comment by cprezzi** [comment]
I agree.

**Comment by jorgerobles** [comment]
I think is 2.1.1 (974 issue) "./node_modules/.bin/electron ." works

**Comment by openhardwarecoza** [comment]
@jorgerobles (: I'm still busy re-npm-ing (slow link = times out ECONNRESET while installing... grrr - even more reason to do the exercise of making it electron.  The webpack dev environment on LW4 and the electron build env total to over 600mb (CD full just to build the 37mb LW4 electron installer (;  

Was your test with electron 1.4.x as is currently in package.json, or 1.6.1 (latest) -  my working test the other day was under 1.4.6 but we cannot use it as chrome 54 (in electron .1.4.6) doesnt support the touchevents/dragevents used in LW4

**Comment by openhardwarecoza** [comment]
Well, answering my own question, launching electron .  on 1.6.1. works (:

![1 6 1](https://cloud.githubusercontent.com/assets/7695323/23246219/c1ba9b66-f99a-11e6-86a2-8e8ef3790db0.PNG)

Lets see if a build works

**Comment by openhardwarecoza** [comment]
Built and installed:  Working!

![lw4 built using 1 6 1](https://cloud.githubusercontent.com/assets/7695323/23246329/64618b22-f99b-11e6-85f9-41233aca6d96.PNG)

**Comment by DarklyLabs** [comment]
@openhardwarecoza Can you post the exe for us to test?

**Comment by openhardwarecoza** [comment]
@DarklyLabs https://drive.google.com/open?id=0B-UxBll2MapjTVNIVHlzcmdCa2s

**Comment by openhardwarecoza** [comment]
(Win64 Build ... ) (We need to check if we can use Appveyor or something similar to automate builds for win32/64/linux/mac

**Comment by DarklyLabs** [comment]
@openhardwarecoza Just installed it on Win10 64bit. Chrome Version 56.0.2924.87

Installed fine but just displays a white screen when run.

**Comment by openhardwarecoza** [comment]
On first run, windows should bring up that Firewall allow access dialog.  Allow it, then restart laserweb

Also, while its running check in netstat if the webserver came up? netstat -an |find /i "listening" |find /i "8000"

![netstat](https://cloud.githubusercontent.com/assets/7695323/23248905/63c224e2-f9aa-11e6-9f3d-4bddd44b17a5.PNG)

**Comment by DarklyLabs** [comment]
@openhardwarecoza Ok, that could be the problem. Firewall dialog is not appearing.

**Comment by DarklyLabs** [comment]
![capture](https://cloud.githubusercontent.com/assets/14358950/23249401/4ea1bb06-f9f8-11e6-98a3-ee594c3caa62.JPG)

**Comment by DarklyLabs** [comment]
Any other dependancies I might need to have installed?

**Comment by openhardwarecoza** [comment]
Check netstat 

https://github.com/LaserWeb/lw.comm-server/issues/6#issuecomment-281916238

**Comment by openhardwarecoza** [comment]
Here's a build with the devtools turned on https://drive.google.com/open?id=0B-UxBll2MapjUnpvLVZmbFBIVkE - maybe there are clues

**Comment by cojarbi** [comment]
Do we have a build procedure for OSx i can try?

**Comment by cojarbi** [comment]
i get the sam as @DarklyLabs on Windows 10, firewall did appear and re checked is listening and granted access but the screen is white

**Comment by cojarbi** [comment]
This is what i get with the dev tools
<img width="1720" alt="screen shot 2017-02-23 at 7 05 25 am" src="https://cloud.githubusercontent.com/assets/16444438/23258532/b48b4b4c-f996-11e6-8d73-e987ce879616.png">

**Comment by openhardwarecoza** [comment]
@cojarbi 

https://github.com/LaserWeb/lw.comm-server/blob/electron_bundler/README-ELECTRON.md should apply on Mac as well, except the very first step, instead of Windows Build Tools

Instead: 
- python (v2.7 recommended, v3.x.x is not supported) (already installed on Mac OS X)
- Xcode ( You also need to install the Command Line Tools via Xcode. You can find this under the menu Xcode -> Preferences -> Downloads This step will install gcc and the related toolchain containing make)

**Comment by openhardwarecoza** [comment]
@cojarbi any clues on console tab?>

**Comment by cojarbi** [comment]
@openhardwarecoza Console  tab is totally empty
<img width="1718" alt="screen shot 2017-02-23 at 7 10 49 am" src="https://cloud.githubusercontent.com/assets/16444438/23258670/416babf6-f997-11e6-8cf0-4bfc5e4fa50b.png">

**Comment by openhardwarecoza** [comment]
![start](https://cloud.githubusercontent.com/assets/7695323/23258645/c73af98c-f9d1-11e6-9893-ea546fccd986.PNG)

Thats what I get.  One probable problem is maybe because LW4's Webpack bundle-prod isnt working and we use bundle-dev:  I see we are still launching some webpack dev server components. Maybe that causes issues

The socket.io errors is a little weird too as I can connect to the backend... but wont cause this symptom

**Comment by openhardwarecoza** [comment]
Uploading a build with just the lw3 web interface - gimme 10 - slow internet

**Comment by openhardwarecoza** [comment]
Ahaa, finally, I can replicate the issue (:

1) launching a new   mainWindow.loadURL('http://127.0.0.1:8000/anything');  from the exe, comes up blank
2) if I launch it first using 'electron . ', it works, subsequent runs with the exe also works (suspect we have loading issue from electron-builder still, running it once the electron . way caches the page... thats why it works.  

Great now that I can replicte, I can investigate

**Comment by cojarbi** [comment]
I get this in the last step of the build npm run dist
<img width="583" alt="screen shot 2017-02-23 at 7 29 41 am" src="https://cloud.githubusercontent.com/assets/16444438/23259214/0805383e-f99a-11e6-998d-6403df7d8215.png">

**Comment by openhardwarecoza** [comment]
try 'npm install -g electron-builder' then try again

**Comment by cojarbi** [comment]
That did not run, it asked me to run it with admin, i did. Next i run npm run dist and get

Ariels-MBP:lw.comm-server ayahni$ npm run dist

> lw.comm-server@4.0.34 dist /Users/ayahni/lw4build/lw.comm-server
> npm run copy && build


> lw.comm-server@4.0.34 copy /Users/ayahni/lw4build/lw.comm-server
> ncp ../LaserWeb4/dist/ app/lw4/ --limit=6

Error: Config is invalid:
{
  "win": [
    {
      "remoteReleases": "Unknown option"
    },
    "Invalid option object"
  ]
}

Raw validation errors: [
  {
    "keyword": "additionalProperties",
    "dataPath": ".win",
    "schemaPath": "#/additionalProperties",
    "params": {
      "additionalProperty": "remoteReleases"
    },
    "message": "should NOT have additional properties"
  },
  {
    "keyword": "type",
    "dataPath": ".win",
    "schemaPath": "#/properties/win/anyOf/1/type",
    "params": {
      "type": "null"
    },
    "message": "should be null"
  },
  {
    "keyword": "anyOf",
    "dataPath": ".win",
    "schemaPath": "#/properties/win/anyOf",
    "params": {},
    "message": "should match some schema in anyOf"
  }
]
    at /usr/local/lib/node_modules/electron-builder/src/packager.ts:139:13
    at next (native)
    at /usr/local/lib/node_modules/electron-builder/node_modules/jsonfile/index.js:46:5
    at /usr/local/lib/node_modules/electron-builder/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
From previous event:
    at Packager.build (/usr/local/lib/node_modules/electron-builder/out/packager.js:278:11)
    at /usr/local/lib/node_modules/electron-builder/src/builder.ts:217:33
    at next (native)
From previous event:
    at build (/usr/local/lib/node_modules/electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dist"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! lw.comm-server@4.0.34 dist: `npm run copy && build`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the lw.comm-server@4.0.34 dist script 'npm run copy && build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lw.comm-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run copy && build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lw.comm-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lw.comm-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ayahni/lw4build/lw.comm-server/npm-debug.log

**Comment by openhardwarecoza** [comment]
Run git pull, then instead of npm run dist,   do npm run distmac (I added a --mac buildscript)

**Comment by cojarbi** [comment]
getting this 
Ariels-MBP:lw.comm-server ayahni$ npm run distmac

> lw.comm-server@4.0.34 distmac /Users/ayahni/lw4build/lw.comm-server
> npm run copy && build --mac 


> lw.comm-server@4.0.34 copy /Users/ayahni/lw4build/lw.comm-server
> ncp ../LaserWeb4/dist/ app/lw4/ --limit=6

Error: Config is invalid:
{
  "win": [
    {
      "remoteReleases": "Unknown option"
    },
    "Invalid option object"
  ]
}

Raw validation errors: [
  {
    "keyword": "additionalProperties",
    "dataPath": ".win",
    "schemaPath": "#/additionalProperties",
    "params": {
      "additionalProperty": "remoteReleases"
    },
    "message": "should NOT have additional properties"
  },
  {
    "keyword": "type",
    "dataPath": ".win",
    "schemaPath": "#/properties/win/anyOf/1/type",
    "params": {
      "type": "null"
    },
    "message": "should be null"
  },
  {
    "keyword": "anyOf",
    "dataPath": ".win",
    "schemaPath": "#/properties/win/anyOf",
    "params": {},
    "message": "should match some schema in anyOf"
  }
]
    at /usr/local/lib/node_modules/electron-builder/src/packager.ts:139:13
    at next (native)
    at /usr/local/lib/node_modules/electron-builder/node_modules/jsonfile/index.js:46:5
    at /usr/local/lib/node_modules/electron-builder/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
From previous event:
    at Packager.build (/usr/local/lib/node_modules/electron-builder/out/packager.js:278:11)
    at /usr/local/lib/node_modules/electron-builder/src/builder.ts:217:33
    at next (native)
From previous event:
    at build (/usr/local/lib/node_modules/electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "distmac"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! lw.comm-server@4.0.34 distmac: `npm run copy && build --mac `
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the lw.comm-server@4.0.34 distmac script 'npm run copy && build --mac '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lw.comm-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run copy && build --mac 
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lw.comm-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lw.comm-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ayahni/lw4build/lw.comm-server/npm-debug.log
Ariels-MBP:lw.comm-server ayahni$

**Comment by openhardwarecoza** [comment]
Lets fix the webserver issue first. Mac distraction slowing me down (;

**Comment by openhardwarecoza** [comment]
@cojarbi Interesting catch on that error:  I was on electron-builder 13.5 - didnt complain about "remoteReleases"

When I upgraded to 14.1.1 I also got errors about "remoteReleases" - so i removed that from package.json. Git pull and try again

(:

**Comment by openhardwarecoza** [comment]
Progress... (:

![path issue](https://cloud.githubusercontent.com/assets/7695323/23260476/a610bba8-f9da-11e6-8540-ed2a4e2ff292.PNG)

Running the laserweb exe from CMD regains logging - which is quite important - see #7 will add later

And here we see why :8000 listens but doesnt serve content... Path issue!

**Comment by cojarbi** [comment]
Build completed successfully, but getting White screen of death, same as windows

also got this warnings while building, posting here for future reference

Rebuilding native production dependencies for darwin:x64
⚠️  Packaging using asar archive is disabled — it is strongly not recommended.
Please enable asar and use asarUnpack to unpack files that must be externally available.
Packaging for darwin x64 using electron 1.6.1 to dist/mac
⚠️  App is not signed: cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://github.com/electron-userland/electron-builder/wiki/Code-Signing

**Comment by openhardwarecoza** [comment]
Asar is purposely turned off as a test from https://github.com/electron-userland/electron-builder/issues/974#issuecomment-264914579

I suspect enabling it and then pointing node static at the proper ASAR path may actually help, looking at the above discovery

**Comment by openhardwarecoza** [comment]
added the "path" module to construct a better relative path than ./app (see change on https://github.com/LaserWeb/lw.comm-server/commit/d381dc9a120fd3a6ad03e2b4aef39128e91e2c4f - @cprezzi that particular change would do well in master too - its the correct standard for node relative paths, as / and \ on win/linux come into play with ./app (i think you inherited that problem though)

And now it seems to work.  Uploading to Google Drive - holding thumbs that when it gets to your machines it still works (:

Here you go https://drive.google.com/open?id=0B-UxBll2MapjeHRxWmgtZ0FxRDg

**Comment by cojarbi** [comment]
i can open it now in Windows 10 with that executable. Its seems to be working properly but dont have a smoothie stamp to test connection

**Comment by openhardwarecoza** [comment]
cool yes, I have an open issue to handle devtools open/close with keyboard shortcut here https://github.com/LaserWeb/LaserWeb4/issues/169 

You can try the mac compile too (: should work now

**Comment by cojarbi** [comment]
will do tonight, out for the day doing that boring thing we call work

**Comment by openhardwarecoza** [comment]
Ahh man.. We all gotta

**Comment by cheton** [comment]
I had ever encountered a blank screen issue, and I eventually found a solution by ignoring proxy settings. Not sure if it's related to yours, but it's worth a try. 

See sess.setProxy API below:

![](http://i.imgur.com/MWZCH53.jpg)

**Comment by jorgerobles** [comment]
Running on mac! https://drive.google.com/open?id=0B9GOB0erdDVbR3BDeVpzaHAxMEE

**Comment by openhardwarecoza** [comment]
Awesomeness!

**Comment by openhardwarecoza** [comment]
@DarklyLabs 

Mac test: https://drive.google.com/open?id=0B9GOB0erdDVbR3BDeVpzaHAxMEE
Win64 test: https://drive.google.com/open?id=0B-UxBll2MapjeHRxWmgtZ0FxRDg

**Comment by openhardwarecoza** [comment]
@cheton valid point - may encounter users with proxies - would be good to force direct

**Comment by openhardwarecoza** [comment]
@jorgerobles https://github.com/LaserWeb/lw.comm-server/blob/electron_bundler/README-ELECTRON.md#subsequent-updates - @cprezzi pushed some fixes into master on this repo, i have pulled the changes into this branch.  new version 4.0.36 

PS @cprezzi version numbering protogates nicely into electron (;

**Comment by openhardwarecoza** [comment]
As a creepy yet useful side effect of keeping the lw3 test code, and lw4 in the build, means that although the Electron UI launches localhost:8000/lw4, opening chrome you can go to either localhost:8000/lw4 or localhost:8000 (lw3)

**Comment by Pooky1306** [comment]
Works well on my win64 desktop.
Any 32b version (pipo x9) ?

I'm reading your posts diagonally but you guys are doing an awesome job !

www.pentaprisme.com

**Comment by openhardwarecoza** [comment]
Let me build you a 32 bit!  I need it for my nextbook little netbook too

**Comment by FabCreator** [comment]
@Pooky1306 FYI the pipo you will get with the Fabkit is the X9s which is a 64bit :)

**Comment by FabCreator** [comment]
awesome work btw guys, my emails still playing up so just read through another 200 github emails haha its like reading a thriller! Super excited to get LW4 on these machines asap :D

**Comment by Pooky1306** [comment]
@FabCreator good to know ;) Anyway I have another one for the mill.

**Comment by cprezzi** [comment]
@openhardwarecoza Having lw3 and lw4 in parallel was very usefull during testing ;)
I also planned to convert the lw3 testpage later to a responsive mini control pannel, so users can additionally connect with a mobile or tablet to see how far the job is and pause or stop it.
 
We should probaly also discuss how we want to make the version numbering. Especially between lw.comm-server and lw4 itself. Both versions need to match in some way to be "compatible".

I have already created two version numbers in config.js (for lw.comm-server and API-version). Probably we could add the compatible lw4 version also.

The config.js content is also delivered to the frontend, so we could make some checks there and alert the user if updates are needed.

**Comment by openhardwarecoza** [comment]
Updates/releases will be a rather hectic mini project.  Electron-builder /
asar / nutz / squirrel etc all playing together

**Comment by cprezzi** [comment]
No holliday yet? ;)

**Comment by openhardwarecoza** [comment]
Definitely only after a mini holiday!  Else we (read Peter)  may have too
many stress fits and break up the team lol

**Comment by openhardwarecoza** [comment]
Reading material in the meantime:

https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build

and https://github.com/electron-userland/electron-builder/wiki/Auto-Update

**Comment by openhardwarecoza** [comment]
@Pooky1306   - Win32 test: https://drive.google.com/open?id=0B-UxBll2MapjdnhTRDB4UE8yX00

**Comment by openhardwarecoza** [comment]
Mac test: https://drive.google.com/open?id=0B9GOB0erdDVbR3BDeVpzaHAxMEE
Win32 test: https://drive.google.com/open?id=0B-UxBll2MapjdnhTRDB4UE8yX00
Win64 test: https://drive.google.com/open?id=0B-UxBll2MapjRW9nbFlFZ0RrSXc v 4.0.36

**Comment by cojarbi** [comment]
Should we test first for a couple of days and then release?

**Comment by cojarbi** [comment]
@openhardwarecoza what would be the equivalent installer for linux?

**Comment by Pooky1306** [comment]
Thanks Peter. I'll test it this weekend and report back.

**Comment by cojarbi** [comment]
OSx https://drive.google.com/file/d/0B-1--YftWEOrTktnYVN4Y1daNjA/view?usp=sharing v 4.0.36

**Comment by FabCreator** [comment]
I seem unable to get it out of the alarm state?

**Comment by cprezzi** [comment]
I have made some changes today on lw.comm-server and laserweb4 that should solve the alarm problem. Everyting is merged to dev-es6 now and Pater will generate a new electron installer.
Version should be 4.0.40. 

You could also try with dev_comms, but check that lw.comm-server in node_modules is updated to version 4.0.40 (or 4040 in version.txt).

**Comment by cprezzi** [comment]
The stop button (abort job) is now dual state. In alarm state, it clears the alarm, otherwise it sends ctrl-x.

**Comment by DarklyLabs** [comment]
@cprezzi Just tested dev-es6. The second click does not clear the alarm. A $X in the console does clear it.

**Comment by DarklyLabs** [comment]
@cprezzi Solved. The git pull didn't update lw-comm. Deleted and ran installdev got it up to version 4040.
I can confirm the dual-action abort functionality works.
Well done Claudio.

**Comment by openhardwarecoza** [comment]
https://plus.google.com/109807573626040317972/posts/V6m5H3AXAEw (;

**Comment by openhardwarecoza** [comment]
I updated the readme, fixed the caching issue and fixed the devtools button today.  Electron app is again able to run up to date from dev-es6 

I think we can close this now

Next step:  (in LW4.1) automate builds with Appveyor/Travis (;
