### ISSUE TITLE
Looking for API Examples/Tutorials

### ISSUE THREAD

**Issue by professorofmit** [LaserWeb/lw.comm-server#63]
Hello,

I was wondering if anyone could share any examples or tutorials for using Laserweb's API since documentation is pretty scarce?

I'm hoping to be able to connect to the server with python, but I am open to other languages.

**Comment by cprezzi** [comment]
Unfortunately there is only the wiki @ https://github.com/LaserWeb/lw.comm-server/wiki/API-(for-client-communication). 

To see an example client implementation in JS, you could check LaserWeb4's com.js (https://github.com/LaserWeb/LaserWeb4/blob/dev-es6/src/components/com.js).
