### ISSUE TITLE
npm does not install on Ubuntu 20.04

### ISSUE THREAD

**Issue by bianchifan** [LaserWeb/lw.comm-server#83]
For I am not a fan of those overwhelming Apps & Snaps I did my first contact to LaserWeb 3 months ago and followed the manual Raspi installation guide for Ubuntu 19.10 which ran fine.
Last week I upgraded to 20.04 and unfortunately I deleted my comm-server directory so I had to download an actual one.
I tried 2 ways, zip and git, both without success :((

1. More than 90 line of tarball faults within terminal
npm WARN tarball tarball data for arr-flatten@1.1.0 (sha512-L3hKV5R/p5o81R7O02IGnwpDmkp6E982XhtbuwSe3O4qOtMMMtodicASA1Cny2U+aCXcNpml+m4dPsvsJ3jatg==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for 7zip-bin-linux@1.3.1 (sha512-Wv1uEEeHbTiS1+ycpwUxYNuIcyohU6Y6vEqY3NquBkeqy0YhVdsNUGsj0XKSRciHR6LoJSEUuqYUexmws3zH7Q==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for dotenv@8.1.0 (sha512-GUE3gqcDCaMltj2++g6bRQ5rBJWtkWTmqmD0fo1RnnMuUqHNCt2oTPeDnS9n6fKYvlhn7AeBkb38lymBtWBQdA==) seems to be corrupted. Trying one more time.
...
npm WARN tarball tarball data for electron-builder@14.5.3 (sha1-luVGbSDT9anFyrw0qlhq3orvh3o=) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for spawn-rx@3.0.0 (sha512-dw4Ryg/KMNfkKa5ezAR5aZe9wNwPdKlnHEXtHOjVnyEDSPQyOpIPPRtcIiu7127SmtHhaCjw21yC43HliW0iIg==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for 7zip-bin-mac@1.0.1 (sha1-Pmh3i78JJq3GgVlCcHRQXUdVXAI=) seems to be corrupted. Trying one more time.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/majo/.npm/_logs/2020-05-16T06_40_52_324Z-debug.log

2. 500 k error log in .npm (former log only a few k)

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose npm-session a4f71c0eba0f8c56
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall lw.comm-server@4.0.136
7 info lifecycle lw.comm-server@4.0.136~preinstall: lw.comm-server@4.0.136
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 34ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 742ms
16 silly install loadAllDepsIntoIdealTree
17 http fetch GET 200 https://registry.npmjs.org/hdiutil 1138ms
18 http fetch GET 200 https://registry.npmjs.org/hdiutil/-/hdiutil-0.0.6.tgz 84ms
19 silly pacote version manifest for hdiutil@0.0.6 fetched in 1249ms
20 silly pacote version manifest for hdiutil@0.0.6 fetched in 6ms
21 silly resolveWithNewModule hdiutil@0.0.6 checking installable status
22 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 2356ms
23 timing stage:loadIdealTree Completed in 3452ms
24 silly currentTree lw.comm-server@4.0.136
25 silly idealTree lw.comm-server@4.0.136
25 silly idealTree ├── @serialport/parser-byte-length@1.0.5
25 silly idealTree ├── @serialport/parser-cctalk@1.0.5
...
5669 silly decomposeActions install socket.io@1.7.4
5670 silly decomposeActions postinstall socket.io@1.7.4
5671 silly decomposeActions finalize socket.io@1.7.4
5672 silly decomposeActions refresh-package-json socket.io@1.7.4
5673 silly install executeActions
5674 silly doSerial global-install 5016
5675 verbose correctMkdir /home/majo/.npm/_locks correctMkdir not in flight; initializing
5676 verbose lock using /home/majo/.npm/_locks/staging-a5355648142c68e7.lock for /home/majo/lw.comm-server/node_modules/.staging
5677 silly doParallel extract 627
5678 silly extract @types/node@8.10.59
5679 silly extract 7zip-bin-linux@1.3.1
5680 silly extract 7zip-bin-mac@1.0.1
5681 silly extract 7zip-bin-win@2.1.1
...
6800 silly saveTree │ └── socket.io-parser@2.3.1
6800 silly saveTree └── ws@1.1.5
6801 verbose stack Error: sha512-BQqTR06ZXKwKB6rUjeANm3aIZo0rqNbQsrQX5zKEDcNY4rxiu5dvdcfIOaAGuZkhW7jAKJsgKC5TjeURtLVuOQ== integrity checksum failed when using sha512: wanted sha512-BQqTR06ZXKwKB6rUjeANm3aIZo0rqNbQsrQX5zKEDcNY4rxiu5dvdcfIOaAGuZkhW7jAKJsgKC5TjeURtLVuOQ== but got sha512-/n/yRqZp0G8f64GK/XSPS8FeHjTh/bqoWAUu4kjeVln/Faqb1Z//beYjkozGxZPu2Vw/msf602fNeCCS9ATd7A==. (34822 bytes)
6801 verbose stack     at IntegrityStream.[_onEnd] (/usr/share/nodejs/ssri/index.js:86:19)
6801 verbose stack     at IntegrityStream.emit (/usr/share/nodejs/ssri/index.js:59:35)
6801 verbose stack     at IntegrityStream.[maybeEmitEnd] (/usr/share/nodejs/ssri/node_modules/minipass/index.js:350:12)
6801 verbose stack     at IntegrityStream.end (/usr/share/nodejs/ssri/node_modules/minipass/index.js:230:27)
6801 verbose stack     at PassThrough.onend (_stream_readable.js:672:10)
6801 verbose stack     at Object.onceWrapper (events.js:286:20)
6801 verbose stack     at PassThrough.emit (events.js:198:13)
6801 verbose stack     at endReadableNT (_stream_readable.js:1145:12)
6801 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
6802 verbose cwd /home/majo/lw.comm-server
6803 verbose Linux 5.4.0-29-generic
6804 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
6805 verbose node v10.19.0
6806 verbose npm  v6.14.4
6807 error code EINTEGRITY
6808 error Verification failed while extracting serialport@6.2.2:
6808 error Verification failed while extracting serialport@6.2.2:
6808 error sha512-BQqTR06ZXKwKB6rUjeANm3aIZo0rqNbQsrQX5zKEDcNY4rxiu5dvdcfIOaAGuZkhW7jAKJsgKC5TjeURtLVuOQ== integrity checksum failed when using sha512: wanted sha512-BQqTR06ZXKwKB6rUjeANm3aIZo0rqNbQsrQX5zKEDcNY4rxiu5dvdcfIOaAGuZkhW7jAKJsgKC5TjeURtLVuOQ== but got sha512-/n/yRqZp0G8f64GK/XSPS8FeHjTh/bqoWAUu4kjeVln/Faqb1Z//beYjkozGxZPu2Vw/msf602fNeCCS9ATd7A==. (34822 bytes)
6809 verbose exit [ 1, true ]

**Comment by cprezzi** [comment]
Please try again with Node v12. We have updated some dependencies and didn't update the wiki in time. Sorry.
You might also need to install serialport separately with `npm install serialport` .
