### ISSUE TITLE
Remove Laserweb from Raspberry

### ISSUE THREAD

**Issue by Dane809** [LaserWeb/lw.comm-server#85]
Can´t remove laserweb from raspberry pi. How can I do that?

**Comment by cprezzi** [comment]
Did you try to delete the lw.comm-servcer folder?

**Comment by Dane809** [comment]
Yes. The version is still 4.0.136
Want to install the newest version, because my settings -> tools don´t work correctly. Can´t open and save the machine settings (other issue)

Thx for your answer @cprezzi 
Great support!

**Comment by cprezzi** [comment]
4.0.136 is the actual version of lw.comm-server. Nothing newer available.

Where do you run the frontend? On the Raspberry Pi or another PC in the network?

**Comment by Dane809** [comment]
Another PC in the network. 
Tools and macros are not "clickable" from the PC

**Comment by cprezzi** [comment]
Then you need to install / reinstall the LaserWeb binary (EXE) on that network PC from here:
https://github.com/LaserWeb/LaserWeb4-Binaries/releases

**Comment by Dane809** [comment]
Sounds like there is a bug in the webinterface of the raspberry?
Today I use the ui with chrome on my pc with the raspberry ip-adress and port 8000.

**Comment by cprezzi** [comment]
I have now updated the hosted frontend files in the app folder of lw.comm-server. Try to make a "git pull" on your raspi (or download and unzip).

**Comment by Dane809** [comment]
Hey, 
will try it today. 
Thx a lot!
