### ISSUE TITLE
sudo node server.js - websockets.listen is not a function

### ISSUE THREAD

**Issue by filka96** [LaserWeb/lw.comm-server#90]
Using https://laserweb.yurl.ch/documentation/installation/36-install-raspberry-pi

**Comment by filka96** [comment]
Fix: 
replace
`var io = websockets.listen(app);`
to
`var io = websockets(app);`

**Comment by cprezzi** [comment]
Are you sure you have installed NodeJS 10?

**Comment by cprezzi** [comment]
This should be solved now and documentation on laserweb.yurl.ch was updated.
The actual version is based on Node.js >= V12.22.5 (which is the default on actual Raspbian Buster or Bullseye).
