### ISSUE TITLE
How can I build a Windows standalone exe?

### ISSUE THREAD

**Issue by mfadel85** [LaserWeb/lw.comm-server#92]
Hello everyone,
How can I build a Windows standalone binary EXE from the source code, to run the project without the need to any browser?
I didn't find any document or guidance

Thank you very much

**Comment by mfadel85** [comment]
is npm run dist enough?
I tried it, it didn't work  it says ncp is not defined I am working on this.

**Comment by cprezzi** [comment]
You need to use the electron_bundler branch to compile an executable. Check out the scripts in package.json. 
If you don't have "ncp" in your shell, you can change the script to "cp" (which is available on most shells).

**Comment by mfadel85** [comment]
@cprezzi Thank you very much

**Comment by mfadel85** [comment]
I have a problem in the last step,  when running npm run dist
Error: Windows icon size must be at least 256x256, please fix "...\lw.comm-server\app\favicon.ico"
but the icon is being generated automatically, how can I change its setting to be 256x256??
I didn't find it any place to change the resolution of the favicon.

**Comment by cprezzi** [comment]
There is a wrong icon defined for windows in package.json line 74 (see: https://github.com/LaserWeb/lw.comm-server/blob/electron_bundler/package.json#L74).
Try to change this line from:
      "icon": "app/favicon.ico"
to
      "icon": "build/icon.ico"

**Comment by mfadel85** [comment]
@cprezzi thank you, it worked
